services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - testcreator-network

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - testcreator-network

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./promtail.yml:/etc/promtail/promtail.yml
      - ../logs:/app/logs # App logs from the Spring Boot app
      - /var/run/docker.sock:/var/run/docker.sock # To read logs from other containers
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - loki
    networks:
      - testcreator-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
    networks:
      - testcreator-network

networks:
  testcreator-network:
    name: test-creator_testcreator-network
    external: true
